
# Intro to Data Science Bootcamp: Day 1



In [325]:
from datetime import date
print 'Dated :' + str(date.today())

Dated :2017-10-27


## Why Python? Some Facts! 


1. Python is a great object-oriented, interpreted, interactive and functional programming language.  
2. Python is a widely used high-level programming language for general-purpose programming.
3. Python was created by Guido van Rossum and first released in 1991.
4. Python emphasizes code readability by supporting whitespace indentation.
5. Python Interpreters are available for pretty much all Operating systems.
6. Python is one of the most successful open-source platform. (CPython is managed by the non-profit Python Software Foundation.)

##### Some of great applications supported in python: to name a few

1. Youtube
2. Survey Monkey
3. Google
4. Quora
5. Bitly
6. Instagram
7. Bitly
8. Spotify
9. NASA
and many more......... 

### Key Features


1. Everything is an object
2. Scalable 
3. Interactive shell
4. Cross Platform


### Releases History

1. 1.0 in 1994
2. 2.0 in 2000
3. 3.0 in 2008

2.7 & 3.6 is pretty reliable distributions

### Python is used for:

1. Web Development: Django, Pyramid, Bottle, Tornado, Flask, web2py
2. GUI Development: tkInter, PyGObject, PyQt, PySide, Kivy, wxPython
3. Scientific and Numeric: SciPy, Pandas, IPython
4. Software Development: Buildbot, Trac, Roundup
5. System Administration: Ansible, Salt, OpenStack


### Getting Python


Installing python: Can easily get from python.org for the needed OS.

https://www.python.org/downloads/


### Hello World In Python! 


In [326]:
print "Hello World!" ## in python 2.7 

Hello World!


In [327]:
2+2

4

If you are writing a script then include this. That way your OS will know whether to invoke compiler or interpretor for same. Example #!/bin/sh for shell scripts
Read more here - https://en.wikipedia.org/wiki/Shebang_(Unix)

In [7]:
#!/usr/bin/python -> Python Shebang 

print "Hello Class!"

Hello Class!


### Code Readability - Indentation

 Python emphasizes on readability, hence it provides indentation. Prefer using tab to do indentation instead of space to make it more readable.

In [10]:
a = 2
if a == 2:
    print True
else:
    print False

True


### Comments in python

In [12]:
# One line comment -> this will not execute

In [19]:
# Multiline Comment -> this will not execute

""" This would be a multiline comment
in Python. You can have detailed description about your code
, assumptions, expected results, anything you want to add here
.....
"""

' This would be a multiline comment\nin Python. You can have detailed description about your code\n, assumptions, expected results, anything you want to add here\n.....\n'

In [330]:
# Comment in a function 

def printnum(num):
    '''print the number num
       @param num: object
       @return: null
    '''
    print num

printnum(2)

2


In [26]:
# Comment in a function 

def printnum(num):
    '''print the number a
       @param num: object
       @return: num
    '''
    return num

print printnum(5)
print printnum('Hello')

5
Hello


## Imports & Modules

In [332]:
import numpy as np

np.array([1,2])

array([1, 2])

In [333]:
from datetime import date
date.today()

datetime.date(2017, 10, 28)

## Datatypes

#### Strings


In [337]:
# word as a string
var = 'Class'
print var

# line as a string
var = "This is the first day of class"
print var

# multi-line as a string
var = 'This is the first day of class.  \
This is the first day of class \
This is the first day of class'
print var

# multi-line as a string
var = '''This is the first day of class.  
This is the first day of class 
This is the first day of class.'''
print var

Class
This is the first day of class
This is the first day of class.  This is the first day of class This is the first day of class
This is the first day of class.  
This is the first day of class 
This is the first day of class.


#### Numbers

In [40]:
batch=02
print batch

type(batch) # give you datatype of that variable

2


int

In [41]:
batch=02.2
print batch

type(batch)

2.2


float

#### Null or None

In [338]:
batch=None
if batch == None:
    print 'Yes'
else:
    print 'No'

Yes


###### Some immutable types
1. int, float, long, complex
2. str
3. bytes
4. tuple
5. frozenset
6. Boolean
7. Array

###### Some mutable types
1. byte array
2. list
3. set
4. dict

## Collections

### Lists


A Python list is a collection of Python objects indexed by an ordered sequence of integers starting from zero. 

In [340]:
# Create a sequencial list
a=[0,1,2,3,4]
a = range(5)
print a
type(a)

[0, 1, 2, 3, 4]


list

In [51]:
# list
a = [0, 1, 2, 3, 4]
print a
type(a)

[0, 1, 2, 3, 4]


list

In [76]:
# length of the list

len(a)

5

In [67]:
# access an element using an index

a[2]

2

In [65]:
# get everything after 2nd index

a[2:]

array([2, 3, 4])

In [66]:
# get everything before 2nd index

a[:2]

array([0, 1])

In [133]:
list_example=[5, 10.0, 'sports', (2+4j), 3.14159]

In [134]:
list_example

[5, 10.0, 'sports', (2+4j), 3.14159]

In [106]:
hello='hello'
world='world'

hw = hello +' '+world
hw

'hello world'

In [107]:
hw1 = hw + ' Class!'
hw1

'hello world Class!'

In [108]:
hw

'hello world'

#### Lists are mutable

In [97]:
# append an item

sports = []

sports.append('Cricket')
sports.append('Tennis')
sports.append('Badminton')
sports.append('Baseball')
sports.append('Chess')

sports

['Cricket', 'Tennis', 'Badminton', 'Baseball', 'Chess']

In [98]:
sports.append('Hockey')

In [99]:
sports

['Cricket', 'Tennis', 'Badminton', 'Baseball', 'Chess', 'Hockey']

In [88]:
# Lists are mutable

sports_new = sports

sports_new.append('Football')

sports_new

['Cricket', 'Tennis', 'Badminton', 'Baseball', 'Chess', 'Hockey', 'Football']

In [89]:
sports

['Cricket', 'Tennis', 'Badminton', 'Baseball', 'Chess', 'Hockey', 'Football']

In [92]:
sports.remove('Tennis')


In [93]:
sports

['Cricket', 'Badminton', 'Baseball', 'Chess', 'Hockey', 'Football']

In [94]:
sports_new

['Cricket', 'Badminton', 'Baseball', 'Chess', 'Hockey', 'Football']

## numpy array

NumPy has a number of functions for creating arrays. You can process and transform all the elements of an array in one command.

In [111]:
# import numpy
import numpy as np

# 1-D Array
b_list=[0, 1, 2, 3, 4]
print type(b_list)
b_nparray = np.array(b_list)
print b_nparray
print type(b_nparray)

<type 'list'>
[0 1 2 3 4]
<type 'numpy.ndarray'>


In [114]:
print b_nparray+2
print type(b_nparray)

[2 3 4 5 6]
<type 'numpy.ndarray'>


In [115]:
print b_nparray/2
print type(b_nparray)

[0 0 1 1 2]
<type 'numpy.ndarray'>


In [116]:
print b_nparray%2
print type(b_nparray)

[0 1 0 1 0]
<type 'numpy.ndarray'>


In [117]:
print b_nparray**2
print type(b_nparray)

[ 0  1  4  9 16]
<type 'numpy.ndarray'>


In [123]:
# 2D Array


b_2D = np.array([[1, 2, 3], [4, 5, 6]])
print b_2D

[[1 2 3]
 [4 5 6]]


In [124]:
# element 6
print b_2D[1][2]

6


In [126]:
# Transpose of matrix

b_2D_T = b_2D.T

print b_2D_T

[[1 4]
 [2 5]
 [3 6]]


In [130]:
# element 6

print b_2D_T[2][1]

6


In [132]:
# get size of 2D arrays

print b_2D.shape
print b_2D_T.shape

(2, 3)
(3, 2)


### Between lists and arrays

1. Lists and Arrays are superficially similar.
2. They are both multi-element data structures.
3. Lists are part of the core Python programming language
4. Arrays are a part of the numerical computing package NumPy. (import numpy)
5. All NumPy array must all be of the same type, whereas the elements of a Python list is homogeneous
6. NumPy arrays support "vectorized" operations meaning element-by-element operations. whereas lists are not vectorized
7. A new NumPy array is created everytime on adding one or more additional elements as it's destroys the old one. Lists retains the old one. Makes it more efficient in large lists.



### Dictionaries

A dictionary is also collection of Python objects, just like a list, but one that is indexed by strings or numbers (not necessarily integers and not in any particular order) or even tuples!

In [344]:
# Define a dictionary 
sports_dict = {}

sports_dict['India']=['Cricket','Hockey']
sports_dict['Spain']='Football'
sports_dict['USA']=['Tennis']

In [345]:
print sports_dict

{'India': ['Cricket', 'Hockey'], 'USA': ['Tennis'], 'Spain': 'Football'}


In [254]:
print sports_dict['Spain']

Football


In [255]:
sports_dict['USA']='Chess'

In [256]:
print sports_dict

{'India': ['Cricket', 'Hockey'], 'USA': 'Chess', 'Spain': 'Football'}


In [257]:
print sports_dict['India']

['Cricket', 'Hockey']


Any immutable object can be the dictionary key.

In [258]:
# length of dictionary

print len(sports_dict)


3


In [341]:
# get keys 

print sports_dict.keys()

# get values
print sports_dict.values()

['India', 'USA', 'Spain']
[['Cricket', 'Hockey', 'TT'], 'Chess', 'Football']


In [261]:
# key-value in dictionary

for key in sports_dict.keys():
    print sports_dict[key]

['Cricket', 'Hockey']
Chess
Football


In [262]:
# if key exists

if sports_dict.has_key('India'):
    print True
else:
    print False
    
if sports_dict.has_key('London'):
    print True
else:
    print False


True
False


In [263]:
# Add 1 more sport to India

sports_dict['India'].append('TT')

In [264]:
sports_dict['India']

['Cricket', 'Hockey', 'TT']

In [346]:
sports_dict['USA'].append('new sport')

In [347]:
sports_dict['USA']

['Tennis', 'new sport']

### Boolean

Value: True / False

In [172]:
# Usage

flag=True

if flag:
    print 'It is true'
else:
    print 'It is not true'
    
print type(flag)

It is true
<type 'bool'>


### Sets


A set contains an unordered collection of unique and immutable objects. 

In [247]:
sports=['Cricket', 'Tennis', 'Badminton', 'Baseball', 'Chess', 'Tennis']

# removes duplicates from the list
sport_set=set(sports)

print sport_set


set(['Cricket', 'Tennis', 'Baseball', 'Chess', 'Badminton'])


###### Immutable Sets

Sets are implemented in a way, which doesn't allow mutable objects. 


In [245]:

sport_setim = set((['Cricket', 'Tennis', 'Baseball'], ['Chess', 'Badminton']))

TypeError: unhashable type: 'list'

##### Frozensets

Though sets can't contain mutable objects, sets are mutable. 
Frozensets are like sets except that they cannot be changed, i.e. they are immutable:


In [186]:
sports_set = set(['Cricket', 'Tennis', 'Baseball'])
sports_set.add("Hockey")
sports_set

{'Baseball', 'Cricket', 'Hockey', 'Tennis'}

In [187]:
sports_fset = frozenset(['Cricket', 'Tennis', 'Baseball'])
sports_fset.add("Hockey")

sports_fset

AttributeError: 'frozenset' object has no attribute 'add'

### Tuples

1. Tuples are immutable.
2. A tuple is a sequence of values much like a list. 
3. The values stored in a tuple can be any type, and they are indexed by integers. 
4. The important difference is that tuples are immutable. 
5. Tuples are also comparable and hashable so we can sort lists of them and use tuples as key values in Python dictionaries.

In [189]:
sports_tuple = 'Cricket', 'Tennis', 'Baseball'

print type(sports_tuple)

<type 'tuple'>


In [190]:
sports_tuple = ('Cricket', 'Tennis', 'Baseball')

print type(sports_tuple)

<type 'tuple'>


In [197]:
# get value from tuple

print sports_tuple[0]
print sports_tuple[0:2]

Cricket
('Cricket', 'Tennis')


In [199]:
# Example from python.org

txt = 'I want to learn data science!'
words = txt.split()
t = list()
for word in words:
    t.append((len(word), word))

t.sort(reverse=True)

res = list()
for length, word in t:
    res.append(word)

print res

['science!', 'learn', 'want', 'data', 'to', 'I']


## Operators

### Arthmetic 

In [205]:
# Basic math operators

a = 10
a+1, a-2, a*2, a**2, a/2, a%2

(11, 8, 20, 100, 5, 0)

### Logical

In [234]:
a = True
b = True 

print a and b
print a or b
print not a
print not b

True
True
False
False


### Comparisons

In [ ]:
a > b , a < b, a >= b , a <= b, a==b, a != b

## String Manipulations

In [229]:
# Basic String Manipulations

my_string='data'

# get length

print len(my_string)

# get substring
print my_string[1:3]

# concatenate
print my_string + ' science' 

# concatenate
new_my_string= 'Today is '+my_string+' session Day '  + str(1)

print new_my_string

# to lower case
print new_my_string.lower()

# to upper case
print new_my_string.upper()


4
at
data science
Today is data session Day 1
today is data session day 1
TODAY IS DATA SESSION DAY 1


In [350]:
# split the sentence into words & frame the sentence back from words
new_my_string='split,the,sentence,into'

words= new_my_string.split(',') 

print words

# join the words back
sentence = ' '.join(words) 

print sentence

['split', 'the', 'sentence', 'into']
split the sentence into


## Control Flow

#### If-Else

In [242]:
# If-Else

def print_grade(score):
    '''print grades for the given score
    @param score: number
    
    '''
    if score >= 90:
        if score == 100:
            print 'A+'
        else:
            print 'A'
    elif score < 90 and score >= 80:
        print 'B+'
    elif score < 80 and score >= 75:
        print 'B'
    elif score < 75 and score >= 60:
        print 'C'
    else:
        print 'D'

        
print_grade(100)
print_grade(87)
print_grade(70)
print_grade(49)

A+
B+
C
D


### Loops 


#### For Loop

In [248]:
# String array
print sports


for sport in sports:
    print sport

['Cricket', 'Tennis', 'Badminton', 'Baseball', 'Chess', 'Tennis']
Cricket
Tennis
Badminton
Baseball
Chess
Tennis


In [250]:
# numbers array
for i in range(0,5):
    print i

0
1
2
3
4


In [251]:
# manipulate array
for i in range(0,5):
    print i+2

2
3
4
5
6


In [268]:
# dictonaries

for key, value in sports_dict.items():
    print '%s, %s' % (key, value)

India, ['Cricket', 'Hockey', 'TT']
USA, Chess
Spain, Football


#### While Loop

In [272]:
num = 0
while num < 20:
    num += 5
    print num

5
10
15
20


#### List Comprehensions

In [276]:
my_sports = ['My ' + sport for sport in sports]

print my_sports

['My Cricket', 'My Tennis', 'My Badminton', 'My Baseball', 'My Chess', 'My Tennis']


In [277]:
## Equivalent To

for sport in sports:
    print 'My ' + sport

My Cricket
My Tennis
My Badminton
My Baseball
My Chess
My Tennis


In [304]:
if 'Chess' in sports:
    print 'yay!!'
    
if 'TT' in sports:
    print 'yay!!'

yay!!


In [308]:
# print sorted list asc
print sorted(sports)

# print sorted list desc
print sorted(sports, reverse=True)

['Badminton', 'Baseball', 'Chess', 'Cricket', 'Tennis', 'Tennis']
['Tennis', 'Tennis', 'Cricket', 'Chess', 'Baseball', 'Badminton']


## Functions

In [354]:
# Define function
def my_function():
    #print hello function
    print 'Hello Class!'

In [355]:
# print hello function
print 'Hello Class!'

Hello Class!


In [351]:
# Call function
my_function()

Hello Class!


In [286]:
# Positional


def add(a,b):
    return a+b

print add(1,2)
print add('Data', ' Science')
print add(str(1), ' Science')

3
Data Science
1 Science


In [297]:
# Arbitrary Arguments

def my_aa_function(*args,**kwargs):
    for arg in args:
        print arg
        
    for key, val in kwargs.items():
        print '%s %s' % (key, val)
    

my_aa_function(args='hello',  myarg2="data", myarg3='2') 

args hello
myarg2 data
myarg3 2


In [301]:
# Linear Search 

def my_linear_search(mylist,n):
    found=False
    for item in mylist:
        if item == n:
            found=True
            break
        else:
            found=False
    return found   


print my_linear_search([1,4,5,6,2,5,9],2)
print my_linear_search([1,4,5,6,2,5,9],30)

True
False


## Error Handling & Exceptions

In [319]:
## Divide by zero

try:
    a=10
    a/0
except ZeroDivisionError, e:
    print e

integer division or modulo by zero


## File Operations



In [320]:
file = open("fires.csv", "r") 
print file.read() 

"","OBJECTID","FOD_ID","FPA_ID","SOURCE_SYSTEM_TYPE","SOURCE_SYSTEM","NWCG_REPORTING_AGENCY","NWCG_REPORTING_UNIT_ID","NWCG_REPORTING_UNIT_NAME","SOURCE_REPORTING_UNIT","SOURCE_REPORTING_UNIT_NAME","LOCAL_FIRE_REPORT_ID","LOCAL_INCIDENT_ID","FIRE_CODE","FIRE_NAME","ICS_209_INCIDENT_NUMBER","ICS_209_NAME","MTBS_ID","MTBS_FIRE_NAME","COMPLEX_NAME","FIRE_YEAR","DISCOVERY_DATE","DISCOVERY_DOY","DISCOVERY_TIME","STAT_CAUSE_CODE","STAT_CAUSE_DESCR","CONT_DATE","CONT_DOY","CONT_TIME","FIRE_SIZE","FIRE_SIZE_CLASS","LATITUDE","LONGITUDE","OWNER_CODE","OWNER_DESCR","STATE","COUNTY","FIPS_CODE","FIPS_NAME","Shape"
"1",1,1,"FS-1418826","FED","FS-FIRESTAT","FS","USCAPNF","Plumas National Forest","0511","Plumas National Forest","1","PNF-47","BJ8K","FOUNTAIN",NA,NA,NA,NA,NA,2005,2453403.5,33,"1300",9,"Miscellaneous",2453403.5,33,"1730",0.1,"A",40.03694444,-121.00583333,5,"USFS","CA","63","063","Plumas",


In [321]:
file = open("testfile.txt","w") 
 
file.write("Hello World!") 
 
file.close() 

In [322]:
file = open("testfile.txt", "r") 
print file.read() 

Hello World!


# References:

    https://docs.python.org/
    http://anh.cs.luc.edu/python/hands-on/3.1/Hands-onPythonTutorial.pdf